### ISSUE TITLE
Feature: Ball State

### ISSUE THREAD

**Issue by LiamFenneman** [LiamFenneman/COMP112-Assignment6#1]
# Feature Title

Ball State

## Feature Description

The state of a ball consists of
- its horizontal position
- its height above the floor (from the floor to the bottom of the Ball)
- its horizontal speed - how far it will move to the right in each step
- its vertical speed - how far it will move up (or down if the speed is negative) in each step, and
- its color

## List of Tasks (Complete in order)

1. [x] Task 1: Implement State Fields
2. [x] Task 2: Ball Constructor
3. [x] Task 3: Horizontal Position Method #2 
4. [x] Task 4: Height Method #3 
5. [x] Task 5: Set Speed Method #5
